# Generated by Django 2.0.5 on 2018-05-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('adhar_number', models.IntegerField(max_length=12)),
                ('phone_number', models.IntegerField(max_length=10)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
